// File generated by FlutterFire CLI (Mocked for development)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'mock-api-key',
    appId: '1:1234567890:web:mockappid',
    messagingSenderId: '1234567890',
    projectId: 'mock-project-id',
    authDomain: 'mock-project-id.firebaseapp.com',
    storageBucket: 'mock-project-id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFagLW0WxVk7q89wgKrhFKz6l75smYeh4',
    appId: '1:618606255653:android:f68272f7cda0d3f09d69cc',
    messagingSenderId: '618606255653',
    projectId: 'salon-notification-19fb5',
    storageBucket: 'salon-notification-19fb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'mock-api-key',
    appId: '1:1234567890:ios:mockappid',
    messagingSenderId: '1234567890',
    projectId: 'mock-project-id',
    storageBucket: 'mock-project-id.appspot.com',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'mock-api-key',
    appId: '1:1234567890:ios:mockappid',
    messagingSenderId: '1234567890',
    projectId: 'mock-project-id',
    storageBucket: 'mock-project-id.appspot.com',
    iosBundleId: 'com.example.customerApp',
  );
}
