<?php

namespace Database\Seeders;

use App\Models\NotificationTemplate;
use App\Support\Notifications\NotificationType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class NotificationTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $templates = [
            // Customer Events
            [
                'key' => 'salon_closure_customer',
                'name' => 'Salon Closure',
                'description' => 'Sent to customers when a salon unexpectedly closes, releasing their booking.',
                'category' => 'Salon',
                'default_push_title' => 'Your appointment needs a new time',
                'default_push_message' => '{{salon_name}} is closed on {{date_label}}. Tap to reschedule.',
                'type' => NotificationType::SALON_CLOSURE,
                'audience' => 'customer',
                'default_title' => 'Your appointment needs a new time',
                'default_message' => '{{salon_name}} is closed on {{date_label}}{{reason}}. Your booking has been released and you can pick a new slot free of charge — the amount you already paid carries over.',
                'available_variables' => ['salon_name', 'date_label', 'reason'],
                'channels' => ['in_app', 'push', 'whatsapp'],
            ],
            [
                'key' => 'booking_created_customer',
                'name' => 'Booking Created (Awaiting Payment)',
                'description' => 'Sent to a customer right after they request a booking to ask for advance payment.',
                'category' => 'Booking',
                'default_push_title' => 'Complete your payment',
                'default_push_message' => 'Pay {{advance_due}} to confirm your booking at {{salon_name}}.',
                'type' => NotificationType::BOOKING_CREATED,
                'audience' => 'customer',
                'default_title' => 'Booking created — complete the payment',
                'default_message' => 'Your booking at {{salon_name}} is held. Pay {{advance_due}} to confirm it.',
                'available_variables' => ['salon_name', 'advance_due'],
                'channels' => ['in_app', 'push'],
            ],
            [
                'key' => 'booking_confirmed_customer',
                'name' => 'Appointment Confirmed',
                'description' => 'Sent to the customer when their booking is successfully confirmed.',
                'category' => 'Booking',
                'default_push_title' => 'Your appointment is confirmed!',
                'default_push_message' => '{{salon_name}} • {{date_label}}',
                'type' => NotificationType::BOOKING_CONFIRMED,
                'audience' => 'customer',
                'default_title' => 'Booking confirmed',
                'default_message' => 'Your booking at {{salon_name}} on {{date_label}} is confirmed.',
                'available_variables' => ['salon_name', 'date_label', 'advance_amount'],
                'channels' => ['in_app', 'push', 'whatsapp'],
            ],
            [
                'key' => 'booking_cancelled_customer',
                'name' => 'Booking Cancelled',
                'description' => 'Sent to the customer when their booking is cancelled.',
                'category' => 'Booking',
                'default_push_title' => 'Booking Cancelled',
                'default_push_message' => 'Your booking at {{salon_name}} on {{date_label}} was cancelled.',
                'type' => NotificationType::BOOKING_CANCELLED,
                'audience' => 'customer',
                'default_title' => 'Booking cancelled',
                'default_message' => 'Your booking at {{salon_name}} on {{date_label}} has been cancelled.',
                'available_variables' => ['salon_name', 'date_label', 'reason'],
                'channels' => ['in_app', 'push', 'whatsapp'],
            ],
            [
                'key' => 'booking_rescheduled_customer',
                'name' => 'Booking Rescheduled',
                'description' => 'Sent to the customer when their booking is moved to a new time.',
                'category' => 'Booking',
                'default_push_title' => 'Booking Rescheduled',
                'default_push_message' => 'Your booking at {{salon_name}} is now on {{date_label}}.',
                'type' => NotificationType::BOOKING_RESCHEDULED,
                'audience' => 'customer',
                'default_title' => 'Booking rescheduled',
                'default_message' => 'Your booking at {{salon_name}} has moved to {{date_label}}.',
                'available_variables' => ['salon_name', 'date_label'],
                'channels' => ['in_app', 'push'],
            ],
            [
                'key' => 'appointment_reminder_customer',
                'name' => 'Appointment Reminder',
                'description' => 'Sent automatically before an upcoming appointment.',
                'category' => 'Appointment',
                'default_push_title' => 'Your appointment is coming up!',
                'default_push_message' => '{{salon_name}} • {{date_label}}',
                'type' => NotificationType::APPOINTMENT_REMINDER,
                'audience' => 'customer',
                'default_title' => 'Reminder: your appointment is coming up',
                'default_message' => 'You are booked at {{salon_name}} on {{date_label}}.',
                'available_variables' => ['salon_name', 'date_label', 'salon_address'],
                'channels' => ['in_app', 'push', 'whatsapp'],
            ],
            [
                'key' => 'appointment_no_show_customer',
                'name' => 'Missed Appointment',
                'description' => 'Sent to the customer when they are marked as a no-show.',
                'category' => 'Appointment',
                'default_push_title' => 'You missed your appointment',
                'default_push_message' => 'Your booking at {{salon_name}} was marked as missed.',
                'type' => NotificationType::APPOINTMENT_NO_SHOW,
                'audience' => 'customer',
                'default_title' => 'Your appointment was missed',
                'default_message' => 'The booking at {{salon_name}} was marked as missed because nobody checked in.',
                'available_variables' => ['salon_name'],
                'channels' => ['in_app', 'push'],
            ],
            [
                'key' => 'appointment_completed_customer',
                'name' => 'Review Request',
                'description' => 'Sent after an appointment to ask for a review.',
                'category' => 'Appointment',
                'default_push_title' => 'How was your visit?',
                'default_push_message' => 'Rate your experience at {{salon_name}}.',
                'type' => NotificationType::APPOINTMENT_COMPLETED,
                'audience' => 'customer',
                'default_title' => 'How was your visit?',
                'default_message' => 'Your appointment at {{salon_name}} is complete. Rate your experience.',
                'available_variables' => ['salon_name'],
                'channels' => ['in_app', 'push'],
            ],

            // Partner Events
            [
                'key' => 'provider_appointment_rescheduled_partner',
                'name' => 'Appointment Rescheduled',
                'description' => 'Sent to the salon when a customer reschedules.',
                'category' => 'Appointment',
                'default_push_title' => 'Appointment Rescheduled',
                'default_push_message' => '{{customer_name}} rescheduled to {{date_label}}.',
                'type' => NotificationType::PROVIDER_APPOINTMENT_RESCHEDULED,
                'audience' => 'partner',
                'default_title' => 'Appointment Rescheduled',
                'default_message' => 'Your appointment with {{customer_name}} on {{date_label}} has been rescheduled by the customer.',
                'available_variables' => ['customer_name', 'date_label'],
                'channels' => ['in_app', 'push'],
            ],
            [
                'key' => 'new_booking_salon_admin',
                'name' => 'New Booking (Salon Admin)',
                'description' => 'Sent to the salon admin when a customer books an appointment.',
                'category' => 'Booking',
                'default_push_title' => 'New Booking: {{customer_name}}',
                'default_push_message' => '{{date_label}}',
                'type' => NotificationType::NEW_BOOKING,
                'audience' => 'salon_admin',
                'default_title' => 'New booking',
                'default_message' => '{{customer_name}} booked {{date_label}} at {{salon_name}}.',
                'available_variables' => ['customer_name', 'date_label', 'salon_name'],
                'channels' => ['in_app', 'push'],
            ],
            [
                'key' => 'new_appointment_service_provider',
                'name' => 'New Appointment (Service Provider)',
                'description' => 'Sent to the service provider when a customer books an appointment.',
                'category' => 'Booking',
                'default_push_title' => 'New Booking: {{customer_name}}',
                'default_push_message' => '{{date_label}}',
                'type' => NotificationType::NEW_BOOKING,
                'audience' => 'service_provider',
                'default_title' => 'New booking',
                'default_message' => '{{customer_name}} booked {{date_label}} at {{salon_name}}.',
                'available_variables' => ['customer_name', 'date_label', 'salon_name'],
                'channels' => ['in_app', 'push'],
            ],
            [
                'key' => 'assigned_salon_expiring_partner',
                'name' => 'Onboarded Salon Expiring',
                'description' => 'Sent to a collaborator when a salon they onboarded is about to expire.',
                'category' => 'Partner',
                'default_push_title' => 'Action required: {{salon_name}} expires soon',
                'default_push_message' => 'Call {{owner_name}} to renew their plan.',
                'type' => NotificationType::ASSIGNED_SALON_EXPIRING,
                'audience' => 'partner',
                'default_title' => '{{salon_name}}\'s plan ends {{when}}',
                'default_message' => 'A salon you onboarded is about to stop taking bookings. Give {{owner_name}} a call before it goes offline.',
                'available_variables' => ['salon_name', 'when', 'owner_name'],
                'channels' => ['in_app', 'push'],
            ],
            [
                'key' => 'assigned_salon_expired_partner',
                'name' => 'Onboarded Salon Expired',
                'description' => 'Sent to a collaborator when a salon they onboarded has expired.',
                'category' => 'Partner',
                'default_push_title' => '{{salon_name}} went offline',
                'default_push_message' => 'Their plan has expired.',
                'type' => NotificationType::ASSIGNED_SALON_EXPIRING, // reused type from before
                'audience' => 'partner',
                'default_title' => '{{salon_name}}\'s plan has expired',
                'default_message' => '{{salon_name}} is no longer taking bookings. Call {{owner_name}} to get it back online.',
                'available_variables' => ['salon_name', 'owner_name'],
                'channels' => ['in_app', 'push'],
            ],
            [
                'key' => 'assigned_salon_renewed_partner',
                'name' => 'Onboarded Salon Renewed',
                'description' => 'Sent to a collaborator when their onboarded salon renews their plan.',
                'category' => 'Partner',
                'default_push_title' => '{{salon_name}} is renewed!',
                'default_push_message' => '{{owner_name}} just paid for {{plan_name}}.',
                'type' => NotificationType::ASSIGNED_SALON_RENEWED,
                'audience' => 'partner',
                'default_title' => '{{salon_name}} is renewed',
                'default_message' => '{{owner_name}} renewed {{plan_name}}. {{live_until_msg}}',
                'available_variables' => ['salon_name', 'owner_name', 'plan_name', 'live_until_msg'],
                'channels' => ['in_app', 'push'],
            ],
            // Owner / Admin notifications
            [
                'key' => 'subscription_expiring_partner',
                'name' => 'Plan Expiring Soon',
                'description' => 'Sent to the salon owner when their subscription is about to end.',
                'category' => 'Account',
                'default_push_title' => 'Your plan ends in {{days_left}} day(s)',
                'default_push_message' => 'Renew {{salon_name}} now to stay listed.',
                'type' => 'subscription_expiring',
                'audience' => 'partner',
                'default_title' => 'Your plan ends in {{days_left}} day{{s}}',
                'default_message' => '{{salon_name}} stops taking online bookings when the plan ends. Renew now to stay listed.',
                'available_variables' => ['days_left', 's', 'salon_name'],
                'channels' => ['in_app', 'push'],
            ],
            [
                'key' => 'subscription_expired_partner',
                'name' => 'Plan Expired',
                'description' => 'Sent to the salon owner when their subscription has expired.',
                'category' => 'Account',
                'default_push_title' => 'Your salon is offline',
                'default_push_message' => '{{salon_name}} has been hidden from customers.',
                'type' => 'subscription_expired',
                'audience' => 'partner',
                'default_title' => 'Your salon is offline',
                'default_message' => '{{salon_name}} has been hidden from customers for {{days_down}}. Your staff cannot use the app either. Renew to go back online.',
                'available_variables' => ['days_down', 'salon_name'],
                'channels' => ['in_app', 'push'],
            ],
            [
                'key' => 'salon_reinstated_partner',
                'name' => 'Salon Reinstated',
                'description' => 'Sent to the salon owner when their salon is put back online.',
                'category' => 'Account',
                'default_push_title' => 'Your salon is back online!',
                'default_push_message' => '{{salon_name}} can now take bookings.',
                'type' => 'salon_reinstated',
                'audience' => 'partner',
                'default_title' => 'Your salon is back online',
                'default_message' => '{{salon_name}} is live again and can take bookings.',
                'available_variables' => ['salon_name'],
                'channels' => ['in_app', 'push'],
            ],
            [
                'key' => 'complaint_warning_partner',
                'name' => 'Complaint Warning',
                'description' => 'Sent to the salon owner when SuperAdmin issues a warning.',
                'category' => 'Account',
                'default_push_title' => 'Warning from BookALook',
                'default_push_message' => 'Please check your notifications.',
                'type' => 'complaint_warning',
                'audience' => 'partner',
                'default_title' => 'A warning from BookALook',
                'default_message' => '{{admin_message}}',
                'available_variables' => ['salon_name', 'admin_message'],
                'channels' => ['in_app', 'push'],
            ],
            [
                'key' => 'complaint_suspension_partner',
                'name' => 'Salon Suspended',
                'description' => 'Sent to the salon owner when their salon is suspended.',
                'category' => 'Account',
                'default_push_title' => 'Your salon is suspended',
                'default_push_message' => 'Please check your notifications for details.',
                'type' => 'salon_suspended',
                'audience' => 'partner',
                'default_title' => 'Your salon has been suspended',
                'default_message' => '{{admin_message}}',
                'available_variables' => ['salon_name', 'admin_message'],
                'channels' => ['in_app', 'push'],
            ],
            // SuperAdmin
            [
                'key' => 'complaint_raised_superadmin',
                'name' => 'Complaint Raised',
                'description' => 'Internal notification for SuperAdmins when a complaint is filed.',
                'category' => 'Other',
                'default_push_title' => 'New complaint',
                'default_push_message' => '{{salon_name}}',
                'type' => 'complaint_raised',
                'audience' => 'superadmin',
                'default_title' => 'Complaint about {{salon_name}}',
                'default_message' => '{{complaint_subject}}',
                'available_variables' => ['salon_name', 'complaint_subject'],
                'channels' => ['in_app'],
            ],
        ];

        foreach ($templates as $template) {
            NotificationTemplate::firstOrCreate(
                ['key' => $template['key']],
                $template
            );
        }
    }
}
